
			<div class="p-footer__access">
				<p class="c-lead">ご入会や、労災保険の加入や申請など、<br class="_sp">お気軽にご相談ください。</p>
				<dl>
					<div class="c-phone">
						<dt>お問い合わせ</dt>
						<dd><a href="tel:0669813365">06-6981-3365</a></dd>
					</div>
					<div class="c-fax">
						<dt>FAX</dt>
						<dd>06-6976-3893</dd>
					</div>
				</dl>
				<p class="c-annotation">窓口対応時間 平日 9:00から17:00まで（土日祝を除く）</p>
				<dl>
					<div class="c-mail">
						<dt>メールアドレス</dt>
						<dd><a href="mailto:info@higashinari-ia.com">info@higashinari-ia.com</a></dd>
					</div>
				</dl>
			</div>