
        <figure class="p-footer__social">
            <figcaption>東成工業会公式SNSはこちらから！</figcaption>
            <ul>
                <li><a href="https://www.facebook.com/%E4%B8%80%E8%88%AC%E7%A4%BE%E5%9B%A3%E6%B3%95%E4%BA%BA-%E6%9D%B1%E6%88%90%E5%B7%A5%E6%A5%AD%E4%BC%9A-100423949305012/" target="_blank" rel="noopener"><img src="/assets/img/cmn/icn_facebook.svg" alt="東成工業会の公式 Facebook へ"></a></li>
<!--                <li><a href=""><img src="/assets/img/cmn/icn_twitter.svg" alt="東成工業会の公式 Twitter へ"></a></li>-->
<!--                <li><a href=""><img src="/assets/img/cmn/icn_line.svg" alt="東成工業会の公式 Line へ"></a></li>-->
<!--                <li><a href=""><img src="/assets/img/cmn/icn_instagram.svg" alt="東成工業会の公式 Instagram へ"></a></li>-->
                <li><a href="https://www.youtube.com/channel/UCObY4kTwuSUNKEk6di-v3OQ/" target="_blank" rel="noopener"><img src="/assets/img/cmn/icn_youtube.svg" alt="東成工業会の公式 YouTube へ"></a></li>
            </ul>
        </figure>