<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-535JWZW"
				  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<!-- block_slip -->
<div class="c-block_slip">
	<a id="PAGE_TOP">ページの先頭です</a>
	<ul>
		<li><a href="#CONTENTS">コンテンツエリアへ</a></li>
		<li><a href="#NAVIGATION">ナビゲーションへ</a></li>
	</ul>
</div><!-- /block_slip -->
