
	<div class="l-header">
		<!-- symbol -->
		<div class="c-symbol"><a href="/"><small>一般社団法人</small><b>東成工業会</b></a></div><!-- /symbol -->

		<!-- global nav -->
		<div class="p-global_nav" id="NAVIGATION">
			<input type="checkbox" id="GLOBAL_NAV_STATUS" class="p-global_nav__status">
			<label for="GLOBAL_NAV_STATUS" class="p-global_nav__open"><span></span></label>
			<nav class="p-global_nav__body" role="navigation">
				<label for="GLOBAL_NAV_STATUS" class="p-global_nav__close"></label>
				<ul class="p-global_nav__list" itemscope itemtype="http://schema.org/SiteNavigationElement">
					<li class="p-global_nav__item" itemprop="name"><a href="/about/" itemprop="url"<?php if($current_id == 'about') echo ' class="is-current"'; ?>>東成工業会について</a></li>
					<li class="p-global_nav__item" itemprop="name"><a href="/guide/" itemprop="url"<?php if($current_id == 'guide') echo ' class="is-current"'; ?>>入会のご案内</a></li>
					<li class="p-global_nav__item" itemprop="name"><a href="/access/" itemprop="url"<?php if($current_id == 'access') echo ' class="is-current"'; ?>>交通アクセス</a></li>
				</ul>

				<!-- お問い合わせバナー -->
				<ul class="p-global_nav__access">
					<li><a href="tel:0669813365" class="c-btn -phone"><small>お問い合わせ</small><b>06-6981-3365</b></a></li>
					<li><a href="mailto:info@higashinari-ia.com" class="c-btn -mail"><small>メール</small><b><img
										src="/assets/img/cmn/icn_mail.svg" alt></b></a></li>
				</ul><!-- /お問い合わせバナー -->
			</nav>
		</div><!-- /global nav -->
	</div>